### ISSUE TITLE
Installing on Windows 10 64 bit error and solution

### ISSUE THREAD

**Issue by Ivan-267** [alex-petrenko/signal-slot#2]
I have been getting errors when trying to install the package on Windows with Conda and Python 3.9 in this case such as (paths abbreviated):

```shell
PS ...\signal-slot-main> pip install .
Processing ...\signal-slot-main
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "...\setup.py", line 35, in <module>
          packages=setuptools.find_packages(where="./", include="signal_slot*"),
        File "...\discovery.py", line 127, in find
          convert_path(str(where)),
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path './' cannot end with '/'
      [end of output]

```

Changing the two paths in setup.py from `./` to just `.` made the install successful, the full modified setup.py was:

```Python
import os

import setuptools
from setuptools import setup

with open("README.md", "r") as f:
    long_description = f.read()
    descr_lines = long_description.split("\n")
    long_description = "\n".join(descr_lines)


queue_deps = ["faster-fifo>=1.4.4,<2.0"] if os.name != "nt" else []


setup(
    # Information
    name="signal-slot-mp",
    description="Fast and compact framework for communication between threads and processes in Python using event loops, signals and slots.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    version="1.0.5",
    url="https://github.com/alex-petrenko/signal-slot",
    author="Aleksei Petrenko",
    license="MIT",
    keywords="asynchronous multithreading multiprocessing queue faster-fifo signal slot event loop",
    project_urls={
        "Github": "https://github.com/alex-petrenko/signal-slot",
        "Sample Factory": "https://github.com/alex-petrenko/sample-factory",
    },
    install_requires=queue_deps,
    extras_require={
        "dev": ["black", "isort", "pytest<8.0", "flake8", "pre-commit", "twine"],
    },
    package_dir={"": "."},
    packages=setuptools.find_packages(where=".", include="signal_slot*"),
    include_package_data=True,
    python_requires=">=3.8",
)
```

I don't have much experience with configuring `setup.py` so I'm not sure if this is the correct way to implement it for Windows and other platforms, I'm just sharing the experience of what caused the error and what seems to work.

After installing the signal-slot that way, I was able to install Sample Factory on Windows without errors as well (before I was receiving errors on install).

**Comment by klyuchnikova-ana** [comment]
Nice!

I think just "." should work. Can you submit a PR please?
